"""empty message

Revision ID: f7b3d939adb0
Revises: 
Create Date: 2019-06-01 14:28:49.759441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7b3d939adb0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ROLES_',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('USERS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['ROLES_.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_USERS_email'), 'USERS', ['email'], unique=True)
    op.create_index(op.f('ix_USERS_username'), 'USERS', ['username'], unique=True)
    op.create_table('POSTS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_POSTS_timestamp'), 'POSTS', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_POSTS_timestamp'), table_name='POSTS')
    op.drop_table('POSTS')
    op.drop_index(op.f('ix_USERS_username'), table_name='USERS')
    op.drop_index(op.f('ix_USERS_email'), table_name='USERS')
    op.drop_table('USERS')
    op.drop_table('ROLES_')
    # ### end Alembic commands ###
